### ISSUE TITLE
Using text embeddings instead of binary embeddings

### ISSUE THREAD

**Issue by luispsantos** [violet-zct/DeMa-BWE#2]
Hello,
Thank you for making available this implementation. I have my own monolingual embeddings in the text format (Word2Vec format). I am wondering whether I can use these embeddings for training bilingual embeddings instead of the FastText binary embeddings. Would it be as simple as replacing calls to load_bin_embeddings(...) in main_e2e.py with read_txt_embeddings(...)?

**Comment by violet-zct** [comment]
Hi,

DeMa-BWE also requires the word counts of each word which can be loaded from the binary model of FastText.  Then DeMa-BWE will use the word counts to computes normalized frequencies of each word. If you are loading word2vec vectors, you need to save the word counts as well.

**Comment by luispsantos** [comment]
Thank you for the reply. I think it would be fairly easy for me to save the word counts for each word separately in a different file. Could I train the bilingual embeddings after having the word2vec vectors and the word counts for the source and target languages?
